const express = require('express')
const router = express.Router()
const controller = require('../../app/controllers/Controller')
const middleware = require('../../app/kernel')
const {query, body} = require('express-validator')
const {Client} = require('../route')

router.post('/', [middleware.authenticate], controller.Client.VisitController.createSchedule)
router.get('/type', [middleware.authenticate], controller.Client.VisitController.getVisitType)
router.get('/', [middleware.authenticate], controller.Client.VisitController.getVisitingSchedule)
router.get('/output', [middleware.authenticate], controller.Client.VisitController.getOutputVisitType)
router.patch('/:visited_oid/checkin', [middleware.authenticate],  controller.Client.VisitController.checkIn)
router.patch('/:visited_oid/checkout', [middleware.authenticate], controller.Client.VisitController.checkOut)
router.get('/:periode/sales', [middleware.authenticate], controller.Client.VisitController.getSalesPerPeriode)
router.post('/customer', [middleware.authenticate], controller.Client.VisitController.createListCustomerToVisit)
router.delete('/:visit_code/delete', [middleware.authenticate], controller.Client.VisitController.deleteSchedule)
router.get('/:visited_oid/detail', [middleware.authenticate], controller.Client.VisitController.getDetailVisiting)
router.get('/:visit_code/schedule', [middleware.authenticate], controller.Client.VisitController.getDetailVisitSchedule)
router.delete('/customer/:visited_oid/delete', [middleware.authenticate], controller.Client.VisitController.deleteFromListSchedule)

module.exports = router