const express = require('express')
const router = express.Router()
const controller = require('../../app/controllers/Controller')
const {Admin} = require('../route')
const middleware = require('../../app/kernel')

router.get(Admin.feature.visitation.visitation, [middleware.adminAuthenticate], controller.Admin.VisitController.visitation)
router.get(Admin.feature.visitation.index_and_create, [middleware.adminAuthenticate], controller.Admin.VisitController.index)
router.get(Admin.feature.visitation.visitation_goal, [middleware.adminAuthenticate], controller.Admin.VisitController.getGoal)
router.get(Admin.feature.visitation.visitation_sales, [middleware.adminAuthenticate], controller.Admin.VisitController.getSales)
router.get(Admin.feature.visitation.visitation_periode, [middleware.adminAuthenticate], controller.Admin.VisitController.getPeriode)
router.get(Admin.feature.visitation.visitation_customer, [middleware.adminAuthenticate], controller.Admin.VisitController.getCustomer)
router.get(Admin.feature.visitation.visitation_output, [middleware.adminAuthenticate], controller.Admin.VisitController.getDataOutput)
router.post(Admin.feature.visitation.index_and_create, [middleware.adminAuthenticate], controller.Admin.VisitController.createSchedule)
router.get(Admin.feature.visitation.visitation_type, [middleware.adminAuthenticate], controller.Admin.VisitController.getTypeVisitation)
router.get(Admin.feature.visitation.visitation_checkin, [middleware.adminAuthenticate], controller.Admin.VisitController.getCheckinData)
router.get(Admin.feature.visitation.visitation_detail, [middleware.adminAuthenticate], controller.Admin.VisitController.detailInvitation)
router.get(Admin.feature.visitation.visitation_code, [middleware.adminAuthenticate], controller.Admin.VisitController.getVisitationCodeSales)
router.get(Admin.feature.visitation.visitation_schedule, [middleware.adminAuthenticate], controller.Admin.VisitController.visitation_schedule)
router.post(Admin.feature.visitation.visitation_create_periode, [middleware.adminAuthenticate], controller.Admin.VisitController.createPeriode)
router.get(Admin.feature.visitation.visitation_sales_quotation, [middleware.adminAuthenticate], controller.Admin.VisitController.getDataSOforSQ)
router.post(Admin.feature.visitation.visitation_visit_customer, [middleware.adminAuthenticate], controller.Admin.VisitController.addNewCustomerToVisit)

module.exports = router