const express = require('express')
const router = express.Router()
const controller = require('../../app/controllers/Controller')
const middleware = require('../../app/kernel')

router.get('/', [middleware.adminAuthenticate], controller.Admin.VisitController.index)
router.get('/sales', [middleware.adminAuthenticate], controller.Admin.VisitController.getSales)
router.post('/', [middleware.adminAuthenticate], controller.Admin.VisitController.createSchedule)
router.get('/periode', [middleware.adminAuthenticate], controller.Admin.VisitController.getPeriode)
router.get('/:userid/goal', [middleware.adminAuthenticate], controller.Admin.VisitController.getGoal)
router.get('/customer', [middleware.adminAuthenticate], controller.Admin.VisitController.getCustomer)
router.get('/type', [middleware.adminAuthenticate], controller.Admin.VisitController.getTypeVisitation)
router.get('/:ptnr_id/sales', [middleware.adminAuthenticate], controller.Admin.VisitController.visitation)
router.post('/visit', [middleware.adminAuthenticate], controller.Admin.VisitController.addNewCustomerToVisit)
router.get('/:user_ptnr_id/output', [middleware.adminAuthenticate], controller.Admin.VisitController.getDataOutput)
router.get('/:userid/code', [middleware.adminAuthenticate], controller.Admin.VisitController.getVisitationCodeSales)
router.get('/:user_ptnr_id/checkin', [middleware.adminAuthenticate], controller.Admin.VisitController.getCheckinData)
router.get('/:visited_oid/detail', [middleware.adminAuthenticate], controller.Admin.VisitController.detailInvitation)
router.get('/:visit_code/schedule', [middleware.adminAuthenticate], controller.Admin.VisitController.visitation_schedule)
router.post('/periode/:visited_oid/detail', [middleware.adminAuthenticate], controller.Admin.VisitController.createPeriode)
router.get('/:user_ptnr_id/sales-quotation', [middleware.adminAuthenticate], controller.Admin.VisitController.getDataSOforSQ)

module.exports = router